# Generated by Django 5.2.7 on 2025-10-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("competition", "競賽"),
                            ("paper", "論文發表"),
                            ("award", "論文獲獎"),
                        ],
                        max_length=20,
                        verbose_name="類別",
                    ),
                ),
                ("event_name", models.CharField(max_length=200, verbose_name="活動名稱")),
                (
                    "work_title",
                    models.CharField(max_length=300, verbose_name="作品/論文標題"),
                ),
                ("award", models.CharField(max_length=100, verbose_name="獲獎/名次")),
                ("event_date", models.DateField(verbose_name="活動日期")),
                (
                    "certificate_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="certificates/",
                        verbose_name="證書圖片",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="詳細描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "成果記錄",
                "verbose_name_plural": "成果記錄",
                "ordering": ["-event_date", "category"],
            },
        ),
        migrations.CreateModel(
            name="LabInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="實驗室名稱")),
                ("full_name", models.CharField(max_length=200, verbose_name="完整名稱")),
                ("founded_date", models.DateField(verbose_name="成立日期")),
                ("slogan", models.CharField(max_length=300, verbose_name="標語")),
                ("mission", models.TextField(verbose_name="使命")),
                ("email", models.EmailField(max_length=254, verbose_name="聯絡信箱")),
                ("github_url", models.URLField(blank=True, verbose_name="GitHub組織")),
                ("website_url", models.URLField(blank=True, verbose_name="官方網站")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "實驗室資訊",
                "verbose_name_plural": "實驗室資訊",
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="標題")),
                ("date", models.DateField(verbose_name="日期")),
                ("content", models.TextField(blank=True, verbose_name="內容")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="是否發布"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "最新消息",
                "verbose_name_plural": "最新消息",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="夥伴名稱")),
                (
                    "partner_type",
                    models.CharField(
                        choices=[
                            ("university", "大學院校"),
                            ("school", "中小學"),
                            ("company", "企業"),
                        ],
                        max_length=20,
                        verbose_name="夥伴類型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("website_url", models.URLField(blank=True, verbose_name="官方網站")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="partners/",
                        verbose_name="Logo",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="顯示順序")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否啟用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "合作夥伴",
                "verbose_name_plural": "合作夥伴",
                "ordering": ["partner_type", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("role", models.CharField(max_length=100, verbose_name="職位")),
                ("description", models.TextField(verbose_name="簡介")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="team/", verbose_name="照片"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="顯示順序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "團隊成員",
                "verbose_name_plural": "團隊成員",
                "ordering": ["order", "name"],
            },
        ),
    ]
